name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.LOCAL_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.LOCAL_SONAR_HOST }}
        with:
          args: >
            -Dsonar.projectKey=testsonar1
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.LOCAL_SONAR_HOST }}
            -Dsonar.login=${{ secrets.LOCAL_SONAR_TOKEN }}
